export { useReducedMotion } from './use-reduced-motion'
export { useDevicePerformance } from './use-device-performance'
export { useMotionPreference } from '@/contexts/motion-context'
export { useCursorState, CursorProvider } from './use-cursor-state'
export { useMagneticEffect } from './use-magnetic-effect'
export { useScrollDirection } from './use-scroll-direction'
export { useActiveSection } from './use-active-section'
export { usePulseSystem } from './use-pulse-system'
export { usePerformanceDegradation } from './use-performance-degradation'
export { useTiltEffect } from './use-tilt-effect'
export { usePreloader } from './use-preloader'
export { useKonamiCode } from './use-konami-code'
export type { DevicePerformance, PerformanceTier } from './use-device-performance'
export type { CursorVariant } from './use-cursor-state'
export type { ScrollDirection } from './use-scroll-direction'
export type { PerformanceLevel } from './use-performance-degradation'
